INSERT INTO referrals(id, hospital_chinese_name, hospital_english_name, number, city)
VALUES (CONVERT(uniqueidentifier, '1f76102d-3a0d-4de5-bda7-c2b3c0ca6ed1'),
        N'國泰綜合醫院', 'Cathay General Hospital', 'cgh-tpe', N'台北市'),
       (NEWID(),
        N'台北市立聯合醫院 陽明院區', 'Taipei City Hospital', 'tch-tpe', N'台北市'),
       (CONVERT(uniqueidentifier, 'B57ADBEC-D138-46A6-AB73-ACDD606E852D'),
        N'國立臺灣大學醫學院 附設醫院兒童醫院', 'National Taiwan University Children''s Hospital', 'ntuch-tpe', N'台北市'),
       (NEWID(),
        N'馬偕紀念醫院 台北院區', 'Mackay Memorial Hospital', 'mmh-tpe', N'台北市'),
       (NEWID(),
        N'三軍總醫院 內湖分院', 'Tri-Service General Hospital', 'tsgh-tpe', N'台北市'),
       (CONVERT(uniqueidentifier, '080BD2B5-F623-4367-AAA1-07B27C4027A0'),
        N'台北市立萬芳醫院', 'Taipei Municipal Wanfang Hospital', 'tmwh-tpe', N'台北市'),
       (NEWID(),
        N'台北和信治癌中心醫院', 'Koo Foundation Sun Yat-Sen Cancer Center', 'kfsyscc-tpe', N'台北市'),
       (NEWID(),
        N'台北榮民總醫院', 'Taipei Veterans General Hospital', 'tvgh-tpe', N'台北市'),
       (NEWID(),
        N'振興醫院', 'Cheng Hsin General Hospital', 'chgh-tpe', N'台北市'),
       (NEWID(),
        N'台北醫學大學附設醫院', 'Taipei Medical University Hospital', 'tmuh-tpe', N'台北市'),
       (NEWID(),
        N'馬偕紀念醫院 淡水院區', 'Mackay Memorial Hospital', 'mmh-ntpc', N'新北市'),
       (CONVERT(uniqueidentifier, 'E4BD0FE7-C6C1-4BF1-A022-6DE3B8C3B15D'),
        N'亞東紀念醫院', 'Far Eastern Memorial Hospital', 'femh-ntpc', N'新北市'),
       (NEWID(),
        N'台北慈濟醫院', 'Taipei Tzu Chi Hospital', 'ttch-ntpc', N'新北市'),
       (NEWID(),
        N'天主教耕莘醫療財團法人耕莘醫院', 'Cardinal Tien Hospital', 'cth-ntpc', N'新北市'),
       (NEWID(),
        N'台中榮民總醫院', 'Taichung Veterans General Hospital', 'tvgh-txg', N'台中市'),
       (NEWID(),
        N'澄清醫院 中港分院', 'Cheng Ching Hospital Chung Kang Branch', 'cchckb-txg', N'台中市'),
       (NEWID(),
        N'中山醫學大學附設醫院', 'Chung Shan Medical University Hospital', 'csmuh-txg', N'台中市'),
       (NEWID(),
        N'中國醫藥大學附設醫院', 'China Medical University Hospital', 'cmuh-txg', N'台中市'),
       (NEWID(),
        N'澄清醫院 平等院區(PIN TIEN)', 'Cheng Ching Hospital', 'cch-txg', N'台中市'),
       (NEWID(),
        N'台中慈濟醫院', 'Taichung Tzu Chi Hospital', 'ttch-txg', N'台中市'),
       (NEWID(),
        N'光田醫院 沙鹿院區', 'Kuang Tien General Hospital', 'ktgh-txg', N'台中市'),
       (NEWID(),
        N'童綜合醫療社團法人 童綜合醫院', 'Tungs''Taichung MetroHarbor Hospital', 'ttmh-txg', N'台中市'),
       (NEWID(),
        N'高雄醫學大學附設中和紀念醫院', 'Kaohsiung Medical University  Hospital', 'kmuh-khh', N'高雄市'),
       (NEWID(),
        N'高雄榮民總醫院', 'Kaohsiung Veterans General Hospital', 'kvgh-khh', N'高雄市'),
       (NEWID(),
        N'阮綜合醫療社團法人阮綜合醫院', 'Yuans General Hospital', 'ygh-khh', N'高雄市'),
       (NEWID(),
        N'高雄市立大同醫院', 'Kaohsiung Municipal Ta-Tung Hospital', 'kmtth-khh', N'高雄市'),
       (NEWID(),
        N'高雄長庚紀念醫院', 'Kaohsiung Chang Gung Memorial Hospital of The C.G.M.F.', 'kcgmh-khh', N'高雄市'),
       (NEWID(),
        N'義大醫療財團法人 義大癌治療醫院', 'E-DA Cancer Hospital', 'edch-khh', N'高雄市');