INSERT INTO checkout_feedback (id,
                               room_state_id,
                               bedding,
                               bedding_feedback,
                               bathroom,
                               bathroom_feedback,
                               refrigerator,
                               refrigerator_feedback,
                               private_item,
                               private_item_feedback,
                               garbage,
                               garbage_feedback,
                               doors_windows_power,
                               doors_windows_power_feedback,
                               security_notification,
                               security_notification_feedback,
                               return_key,
                               return_key_feedback,
                               return_checkin_file,
                               return_checkin_file_feedback)


VALUES (CONVERT(uniqueidentifier, 'f813210d-f40b-4142-ac89-ba4f1884b0db'),
        CONVERT(uniqueidentifier, '24F93F6D-05B2-428A-B578-8431D4BBE372'),
                                       N'未完成',
                                       N'不想摺棉被',
                                       N'已完成',
                                       N'無',
                                       N'已完成',
                                       N'無',
                                       N'已完成',
                                       N'無',
                                       N'已完成',
                                       N'無',
                                       N'已完成',
                                       N'無',
                                       N'已完成',
                                       N'無',
                                       N'已完成',
                                       N'無',
                                       N'已完成',
                                       N'無')



